### PR TITLE
Add ability to have multiple dataset configs

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by dimaskiddo** [comment]
Can you explain how to fill the array?
Is it like:
```
{ 
- dataset: "mydataset1"
   process_childern_only: "true"
   recursive: "true"
- dataset: "mydataset2"
   process_childern_only: "false"
   recursive: "true"
}
```

**Comment by Cadair** [comment]
Just over a year later I came back to this :rofl: 

Yeah, that's how to fill the array, I added a comment explaining.

**Comment by dimaskiddo** [comment]
Can you also change the Inventory Example? 😄

**Comment by Cadair** [comment]
done :)

**Comment by dimaskiddo** [comment]
Thank you so much @Cadair for your contribution 😄

**Pull request merged**
